pipeline:
  # the simplest test in the world
  lint:
    image: php
    commands:
      - |
          rc=0
          for php_file in src/oas-php-source/*.php; do
            php -l $php_file || rc=1
          done
          exit $rc
  publish:
    image: oasplugins/s2i
    destimg: oas0/oas-php-source:${DRONE_COMMIT:0:7}
    secrets:
      - docker_username
      - docker_password
